### ISSUE TITLE
Tagging the latest master to reflect the php version issue

### ISSUE THREAD

**Issue by sunel** [magesuite/product-details-reorder#1]
Tagging the latest master to reflect the php version issue

**Comment by sunel** [comment]
Temp fix for those who come for this issue

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/magesuite/product-details-reorder"
        }
    ],
    "require": {
        "creativestyle/magesuite-product-details-reorder": "1.x-dev as 1.1.1"
    }
}
```

**Comment by manikumaran1978** [comment]
Thank you for your help. But where to add this ?

**Comment by jtomaszewski** [comment]
https://packagist.org/packages/creativestyle/magesuite-product-details-reorder#v1.1.2 fixed it. You can just do `composer update creativestyle/magesuite-product-details-reorder` now to fix it, without the composer.json changes.
